# Generated by Django 5.1.1 on 2024-11-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardSnapshot',
        ),
    ]
