# Generated by Django 5.1 on 2024-10-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0003_alter_contentblock_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='is_active',
        ),
    ]
