# Generated by Django 5.1.1 on 2024-11-08 18:17

import contentblock.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0004_remove_contentblock_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='image',
        ),
        migrations.CreateModel(
            name='ContentBlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[contentblock.validators.validate_image_path])),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contentblock.contentblock')),
            ],
        ),
    ]
