# Generated by Django 5.1.1 on 2024-11-08 18:22

import contentblock.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0005_remove_contentblock_image_contentblockimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[contentblock.validators.validate_image_path]),
        ),
        migrations.DeleteModel(
            name='ContentBlockImage',
        ),
    ]
