# Generated by Django 5.1.1 on 2024-11-09 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_is_active'),
        ('photo', '0004_remove_photo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_cover', to='photo.photo'),
        ),
    ]
