# Generated by Django 5.1.1 on 2024-11-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('sentiment', models.CharField(max_length=20)),
                ('intent', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assistantcontext',
            name='conversation_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assistantcontext',
            name='conversation_turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistantcontext',
            name='last_intent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assistantcontext',
            name='last_topic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
