# Generated by Django 5.1 on 2024-10-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sequence_number']},
        ),
    ]
