# Generated by Django 5.1 on 2024-10-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
